
[Execution]
	#Determines the mininmum amount of health to execute a target. The operation is (this number x execution leve)
	"Min health threshold" = 2.5
	#Determines wether execution should work on bosses
	"Can execute bosses" = true
	#Should Execution exist?
	"Allow Execution" = true

[Wave]
	#Determines wether the wave enchantment should show particles
	"Show Wave" = true
	#Determines how much knockback wave should apply
	"Wave kb" = 0.9
	#Should Wave exist?
	"Allow Wave" = true

["Poison Aspect"]
	#Determines the amount of ticks Poison Aspect should poison for
	"Poison Ticks" = 120.0
	#Should Poison Aspect exist?
	"Allow Poison Aspect" = true
	#Should Poison Aspect be incompatible with Fire Aspect?
	"Incompatible with Fire Aspect" = true
	#Should Poison Aspect be incompatible with Ice Aspect?
	"Incompatible with Ice Aspect" = true

[Auto-Smelting]
	#Should Auto Smelting drop additional xp? (Not much)
	"Drop extra xp" = true
	#Should Auto-Smelting exist?
	"Allow Auto Smelting" = true
	#Should Auto-Smelting be incompatible with Fortune? 
	"Incompatible with Fortune" = true
	#Should Auto-Smelting be incompatible with Enhancement?
	"Incompatible with Enhancement" = true

[Rebirth]
	#How much damage should Rebirth do to a shield?
	"Rebirth Damage" = 50.0
	#Should Rebirth exist?
	"Allow Rebirth" = true

[Stunning]
	#How many ticks should Stunning slow for? (set to 0 to disable its slow effect)
	SlownessTicks = 60.0
	#How many ticks should Stunning weaken the enemy for?
	"Weakness Ticks" = 60.0
	#Should Stunning make noise after a succesful stun?
	"Make noise" = true
	#Should Stunning exist?
	"Allow Stunning" = true

[Agility]
	#This value determines the percentage of speed that Agility should add
	"Speed Percentage" = 15.0
	#Should Agility exist?
	"Allow Agility" = true
	#Should Agility be incompatible with Curse of Slowness?
	"Incompatible with Curse of Slowness" = true
	#Should Agility be incompatible with Jumper
	"Incompatible with Jumper" = true

["Curse of Slowness"]
	#This value determines the percentage of speed that Curse of Slowness should remove
	"Slowness percentage" = 15.0
	#Should Curse of Slowness exist?
	"Allow Curse of Slowness" = true
	#Should Curse of Slowness be incompatible with Agility?
	"Incompatible with Agility" = true
	#Should  Curse of Slowness be incompatible with Jumper?
	"Incompatible with Jumper" = true

["Blood Blade"]
	#Determines the amount of HP divided by 3 that Blood Blade will recuperate each level
	"HP recuperated" = 2.0
	#Should Blood Blade exist?
	"Allow Blood Blade" = true
	#Should Blood Blade be incompatible with Boosting?
	"Incompatible with Boosting" = true
	#Should Blood Blade be incompatible with Looting?
	"Incompatible with Looting" = true

["Sunlight's Blessing"]
	#Determines the amount of seconds Sunlight's Blessing takes to repair a single use of an item
	"Sunlight Seconds" = 3.9999999999999996
	#Should Sunlight's Blessing exist?
	"Allow Sunlight's Blessing" = true
	#Should Sunlight's Blessing be incompatible with Mending?
	"Incompatible with Mending" = true
	#Should Sunlight's Blessing be incompatible with Curse of Moonlight?
	"Incompatible with Curse of Moonlight" = true

[Jumper]
	#Determines the amount of jump boost (in blocks) that Jumper should add
	"Jump Blocks" = 1.0
	#Should Jumper exist?
	"Allow Jumper" = true
	#Should Jumper be incompatible with Agility?
	"Incompatible with Agility" = true
	#Should Jumper be incompatible with Curse of Slowness?
	"Incompatible with Curse of Slowness" = true

["Pain Power"]
	#Determines the HP percentage at which Pain Power should apply its effects
	"Low Health Threshold" = 40.0
	#Determines wether Pain Power should apply speed
	"Should apply Speed" = true
	#Determines wether Pain power should apply  resistance
	"Should apply Resistance" = true
	#Should Pain Power exist?
	"Allow Pain Power" = true

